# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_LOGIN_TOKEN }}
        ref: ${{ github.head_ref }}

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Extract and Increment Version
      id: versioning
      run: |
        # Extract version using Maven
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "Current version: $VERSION"
        
        # Extract major, minor, and patch versions
        MAJOR=$(echo $VERSION | cut -d. -f1)
        MINOR=$(echo $VERSION | cut -d. -f2)
        PATCH=$(echo $VERSION | cut -d. -f3)

        # Increment patch version
        NEW_PATCH=$((PATCH + 1))
        NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"

        echo "New version: $NEW_VERSION"

        # Update version using Maven command
        mvn build-helper:parse-version versions:set -DnewVersion=$NEW_VERSION -DgenerateBackupPoms=false

        # Output new version for later steps
        echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

    - name: Build with Maven
      run: mvn -B package --file pom.xml

#    - name: Build and Push Docker Image
#      run: |
#        mvn spring-boot:build-image
#        docker login docker.io -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
#        docker push docker.io/${{ secrets.DOCKER_USERNAME }}/spring-boot-kubernetes:0.0.1

    - name: Commit Updated pom.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "Daniele Ninicato"
        git config --global user.email "daniele.ninicato@gmail.com"
        git add pom.xml
        git commit -m "Bump version to $NEW_VERSION" || echo "No changes to commit"
        git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}
